/** حالات سريرية تعليمية مبسطة لطالب الصيدلة — ليست بديلًا عن التشخيص الطبي. */

export type ClinicalCase = {
  id: string;
  topic: string;
  title: string;
  level: "مبتدئ" | "متوسط" | "متقدم";
  age: string;
  gender?: string;
  symptoms: string[];
  history?: string[];
  currentDrugs?: { drugId?: string; text: string }[];
  redFlags?: string[];
  question: string;
  options: string[];
  answer: number;
  explanation: string;
  pharmacology: string;
  relatedDrugs: string[];
};

export const clinicalCases: ClinicalCase[] = [
  {
    id: "case-headache",
    topic: "صداع",
    title: "صداع توتري متكرر عند شابة",
    level: "مبتدئ",
    age: "24 سنة",
    gender: "أنثى",
    symptoms: ["صداع ضاغط حول الرأس", "يزداد مع التوتر والسهر", "بدون غثيان أو حساسية للضوء"],
    history: ["لا أمراض مزمنة", "تشرب قهوة بكثرة"],
    redFlags: ["لا يوجد صداع مفاجئ شديد", "لا حمى أو تصلب رقبة"],
    question: "ما الخيار الأول المناسب للصرف في الصيدلية؟",
    options: ["Paracetamol 500–1000 مغ عند الحاجة", "Diclofenac حقن عضلي", "Codeine مركب", "Amoxicillin"],
    answer: 0,
    explanation:
      "الصداع التوتري البسيط يُعالج بمسكن بسيط مثل الباراسيتامول مع تصحيح نمط النوم وتقليل الكافيين.",
    pharmacology:
      "الباراسيتامول يعمل مركزيًا على تثبيط COX ومسارات الألم دون تأثير التهابي محيطي مهم، لذلك أمانه المعدي أعلى من NSAIDs.",
    relatedDrugs: ["paracetamol", "ibuprofen"],
  },
  {
    id: "case-dental",
    topic: "ألم الأسنان",
    title: "ألم أسنان مع تورم خفيف باللثة",
    level: "مبتدئ",
    age: "31 سنة",
    gender: "ذكر",
    symptoms: ["ألم نابض في ضرس سفلي", "تورم موضعي باللثة", "ألم يزداد ليلًا"],
    history: ["لا حساسية دوائية", "لا قرحة معدية"],
    question: "ما المسكن الأنسب لطبيعة الألم الالتهابي هنا؟",
    options: ["Paracetamol فقط", "Ibuprofen 400 مغ بعد الطعام", "Loperamide", "Cetirizine"],
    answer: 1,
    explanation:
      "الألم الالتهابي السني يستجيب أفضل لمضاد التهاب غير ستيرويدي، مع إحالة لطبيب الأسنان لعلاج السبب.",
    pharmacology: "الإيبوبروفين يثبط COX-1/COX-2 فيقلل البروستاغلاندينات المسؤولة عن الالتهاب والألم.",
    relatedDrugs: ["ibuprofen", "paracetamol", "co-amoxiclav"],
  },
  {
    id: "case-fever-child",
    topic: "الحمى",
    title: "طفل بحمى 38.9 درجة",
    level: "مبتدئ",
    age: "4 سنوات (16 كغ)",
    symptoms: ["حمى منذ يوم", "خمول خفيف", "شهية أقل"],
    history: ["ملقّح بالكامل", "لا تشنجات سابقة"],
    redFlags: ["لا طفح جلدي", "لا تصلب رقبة", "يتبول بشكل طبيعي"],
    question: "ما جرعة الباراسيتامول الصحيحة لهذا الطفل؟",
    options: ["500 مغ كل 6 ساعات", "160–240 مغ كل 6 ساعات (10–15 مغ/كغ)", "1 غ مرة واحدة", "50 مغ كل 4 ساعات"],
    answer: 1,
    explanation: "الجرعة للأطفال 10–15 مغ/كغ لكل جرعة، أي حوالي 160–240 مغ لطفل 16 كغ، بما لا يزيد عن 4 جرعات يوميًا.",
    pharmacology: "الجرعة بالأطفال تُحسب بالوزن لأن حجم التوزيع والاستقلاب يختلفان عن البالغين.",
    relatedDrugs: ["paracetamol", "ibuprofen"],
  },
  {
    id: "case-cold",
    topic: "نزلات البرد",
    title: "زكام فيروسي منذ ثلاثة أيام",
    level: "مبتدئ",
    age: "27 سنة",
    symptoms: ["سيلان أنف", "عطاس", "حرارة خفيفة", "بدون ضيق نفس"],
    question: "ما التصرف الصيدلاني الصحيح؟",
    options: [
      "صرف مضاد حيوي مباشرة",
      "علاج داعم للأعراض وتوعية المريض",
      "صرف كورتيزون فموي",
      "صرف Ciprofloxacin",
    ],
    answer: 1,
    explanation: "نزلات البرد فيروسية ذاتية الشفاء؛ المضاد الحيوي لا يفيد ويزيد المقاومة.",
    pharmacology: "المضادات الحيوية تستهدف البكتيريا فقط ولا تأثير لها على الفيروسات التنفسية.",
    relatedDrugs: ["paracetamol", "chlorpheniramine"],
  },
  {
    id: "case-cough",
    topic: "السعال",
    title: "سعال جاف بعد بدء دواء ضغط",
    level: "متوسط",
    age: "58 سنة",
    gender: "ذكر",
    symptoms: ["سعال جاف مزعج", "بدأ بعد 3 أسابيع من دواء جديد", "بدون بلغم أو حمى"],
    currentDrugs: [{ drugId: "lisinopril", text: "Lisinopril 10 mg يوميًا" }],
    question: "ما التفسير الأرجح والتصرف المناسب؟",
    options: [
      "عدوى تنفسية — صرف مضاد حيوي",
      "سعال بسبب ACE inhibitor — إحالة لتغييره إلى ARB",
      "ربو — صرف بخاخ",
      "حساسية — صرف مضاد هيستامين",
    ],
    answer: 1,
    explanation: "السعال الجاف من الآثار المعروفة لمثبطات ACE؛ الحل استبداله بـ ARB مثل Losartan بقرار الطبيب.",
    pharmacology: "تثبيط ACE يقلل تكسير البراديكينين فيتراكم في الطريق التنفسي مسببًا السعال.",
    relatedDrugs: ["lisinopril", "losartan"],
  },
  {
    id: "case-diarrhea",
    topic: "الإسهال",
    title: "إسهال حاد عند طفل مع علامات جفاف خفيفة",
    level: "مبتدئ",
    age: "3 سنوات",
    symptoms: ["إسهال مائي 5 مرات يوميًا", "عطش", "بدون دم في البراز"],
    redFlags: ["لا حمى عالية", "لا دم", "يتبول"],
    question: "ما الأساس في العلاج؟",
    options: ["Loperamide", "أملاح الإماهة الفموية + الزنك", "مضاد حيوي فموي", "Metoclopramide"],
    answer: 1,
    explanation: "الإماهة الفموية هي حجر الأساس، والزنك يقصّر مدة الإسهال عند الأطفال. اللوبيراميد غير مناسب للأطفال.",
    pharmacology: "محلول ORS منخفض الأسمولية يستفيد من الناقل المشترك للصوديوم والجلوكوز في الأمعاء لتعويض السوائل.",
    relatedDrugs: ["ors", "loperamide"],
  },
  {
    id: "case-constipation",
    topic: "الإمساك",
    title: "إمساك مزمن عند سيدة حامل",
    level: "متوسط",
    age: "29 سنة",
    gender: "أنثى — حامل بالشهر السادس",
    symptoms: ["تبرز كل 3 أيام", "براز قاسٍ", "بدون دم"],
    question: "ما الخيار الأنسب؟",
    options: ["Bisacodyl جرعات عالية", "Lactulose مع ألياف وسوائل", "زيت خروع", "Loperamide"],
    answer: 1,
    explanation: "اللاكتولوز ملين تناضحي مقبول في الحمل مع تعديل النظام الغذائي وزيادة السوائل.",
    pharmacology: "اللاكتولوز لا يُمتص ويُخمّر في القولون فيسحب الماء ويلين البراز.",
    relatedDrugs: ["lactulose", "ors"],
  },
  {
    id: "case-gerd",
    topic: "الحموضة و GERD",
    title: "حرقة صدرية متكررة بعد الأكل",
    level: "متوسط",
    age: "42 سنة",
    gender: "ذكر",
    symptoms: ["حرقة خلف القص", "طعم حامض بالفم", "تزداد بالاستلقاء"],
    history: ["زيادة وزن", "تدخين"],
    redFlags: ["لا صعوبة بلع", "لا نقص وزن", "لا قيء دموي"],
    question: "ما التوصية الأنسب؟",
    options: [
      "Omeprazole 20 مغ قبل الفطور + تعديل نمط الحياة",
      "Ibuprofen للألم",
      "Metoclopramide مدى الحياة",
      "لا حاجة لأي إجراء",
    ],
    answer: 0,
    explanation: "مثبط مضخة البروتون قبل الفطور بنصف ساعة هو العلاج الأنسب مع تقليل الوزن والتدخين والوجبات الليلية.",
    pharmacology: "الأوميبرازول يثبط مضخة H+/K+-ATPase في الخلايا الجدارية فيقلل إفراز الحمض لفترة طويلة.",
    relatedDrugs: ["omeprazole", "famotidine"],
  },
  {
    id: "case-allergy",
    topic: "الحساسية",
    title: "حساسية أنف موسمية عند سائق شاحنة",
    level: "مبتدئ",
    age: "35 سنة",
    gender: "ذكر",
    symptoms: ["عطاس وسيلان أنف", "حكة بالعين", "أعراض موسمية"],
    question: "ما مضاد الهيستامين الأنسب لمهنته؟",
    options: ["Chlorpheniramine", "Loratadine 10 مغ يوميًا", "Diphenhydramine ليلًا ونهارًا", "Cetirizine 20 مغ"],
    answer: 1,
    explanation: "الجيل الثاني (لوراتادين) لا يسبب نعاسًا يُذكر، وهو الأنسب لمن يقود المركبات.",
    pharmacology: "مضادات الهيستامين الجيل الثاني لا تعبر الحاجز الدماغي بسهولة، فيقل التأثير المهدئ.",
    relatedDrugs: ["loratadine", "cetirizine", "chlorpheniramine"],
  },
  {
    id: "case-htn",
    topic: "ارتفاع ضغط الدم",
    title: "ارتفاع ضغط مع وذمة كاحلين",
    level: "متوسط",
    age: "55 سنة",
    gender: "أنثى",
    symptoms: ["ضغط 150/95", "تورم بالكاحلين", "بدون ضيق نفس"],
    currentDrugs: [{ drugId: "amlodipine", text: "Amlodipine 10 mg يوميًا" }],
    question: "ما التفسير الأرجح للوذمة؟",
    options: [
      "قصور قلب حتمًا",
      "تأثير جانبي متوقع للأملوديبين",
      "حساسية دوائية",
      "قصور كلوي مؤكد",
    ],
    answer: 1,
    explanation: "وذمة الكاحلين أثر جانبي شائع لحاصرات قنوات الكالسيوم؛ يُناقش تقليل الجرعة أو تغيير المجموعة مع الطبيب.",
    pharmacology: "التوسع الشرياني الانتقائي يرفع الضغط داخل الشعيرات فينتقل السائل للنسيج الخلالي.",
    relatedDrugs: ["amlodipine", "losartan", "hydrochlorothiazide"],
  },
  {
    id: "case-dm",
    topic: "السكري",
    title: "سكري نوع ثاني حديث التشخيص",
    level: "متوسط",
    age: "47 سنة",
    gender: "ذكر",
    symptoms: ["HbA1c 7.8%", "وزن زائد", "وظائف كلى طبيعية"],
    question: "ما الخط الأول الدوائي؟",
    options: ["Insulin مباشرة", "Metformin مع تعديل النمط الغذائي", "Gliclazide", "لا دواء"],
    answer: 1,
    explanation: "الميتفورمين هو الخط الأول لمعظم مرضى النوع الثاني عند سلامة الوظيفة الكلوية.",
    pharmacology: "الميتفورمين يقلل إنتاج الجلوكوز الكبدي ويزيد حساسية الأنسجة للأنسولين دون تحفيز إفراز الأنسولين.",
    relatedDrugs: ["metformin", "gliclazide"],
  },
  {
    id: "case-asthma",
    topic: "الربو",
    title: "استخدام متكرر لبخاخ الإنقاذ",
    level: "متوسط",
    age: "19 سنة",
    gender: "أنثى",
    symptoms: ["تستخدم السالبوتامول 5 مرات أسبوعيًا", "سعال ليلي", "أزيز مع الجهد"],
    currentDrugs: [{ drugId: "salbutamol", text: "Salbutamol MDI عند الحاجة" }],
    question: "ما الاستنتاج والتصرف؟",
    options: [
      "الربو مسيطر عليه — استمرار كما هو",
      "ربو غير مسيطر عليه — إحالة لإضافة كورتيزون استنشاقي",
      "زيادة السالبوتامول لجرعة ثابتة",
      "صرف مضاد حيوي",
    ],
    answer: 1,
    explanation: "الحاجة لبخاخ الإنقاذ أكثر من مرتين أسبوعيًا مؤشر على ربو غير مسيطر عليه ويستدعي علاجًا وقائيًا.",
    pharmacology: "الكورتيزون الاستنشاقي يعالج الالتهاب المزمن الأساسي، بينما موسع القصبات يخفف الأعراض فقط.",
    relatedDrugs: ["salbutamol", "budesonide"],
  },
  {
    id: "case-uti",
    topic: "العدوى الشائعة",
    title: "التهاب مسالك بولية غير معقد",
    level: "متوسط",
    age: "26 سنة",
    gender: "أنثى — غير حامل",
    symptoms: ["حرقة عند التبول", "تبول متكرر", "بدون حمى أو ألم خلفي"],
    question: "ما التصرف الصيدلاني الصحيح؟",
    options: [
      "صرف مضاد حيوي بدون وصفة",
      "إحالة لتقييم طبي واختيار المضاد المناسب + الإماهة",
      "صرف مسكن فقط ورفض الإحالة",
      "صرف كورتيزون",
    ],
    answer: 1,
    explanation: "المضادات الحيوية تُصرف بوصفة؛ دور الصيدلي التوعية والإحالة ودعم الالتزام لاحقًا.",
    pharmacology: "اختيار المضاد يعتمد على نمط المقاومة المحلي وسلامة الكلى والحمل.",
    relatedDrugs: ["ciprofloxacin", "co-amoxiclav", "paracetamol"],
  },
  {
    id: "case-derm",
    topic: "مشاكل جلدية شائعة",
    title: "حكة واحمرار بين أصابع القدم",
    level: "مبتدئ",
    age: "22 سنة",
    gender: "ذكر",
    symptoms: ["تقشر وحكة بين الأصابع", "يزداد مع التعرق", "بدون قيح"],
    question: "ما العلاج الموضعي المناسب؟",
    options: ["Hydrocortisone وحده", "Clotrimazole 1% مرتين يوميًا", "مضاد حيوي كريم", "مطهر فقط"],
    answer: 1,
    explanation: "سعفة القدم عدوى فطرية تُعالج بمضاد فطري موضعي لمدة 2–4 أسابيع مع تجفيف القدم جيدًا.",
    pharmacology: "الكلوتريمازول يثبط إنزيم 14-α-demethylase فيمنع تصنيع الإرغوستيرول في غشاء الفطر.",
    relatedDrugs: ["clotrimazole", "hydrocortisone-topical"],
  },
];

export const caseById = (id: string) => clinicalCases.find((c) => c.id === id);
