/**
 * قاعدة بيانات الأدوية التعليمية — مصدر واحد لكل بطاقات الدواء داخل المنصة.
 * التصنيف يتبع نظام WHO ATC. المحتوى تعليمي مختصر وقابل للتحديث،
 * وليس بديلًا عن المراجع الدوائية الرسمية.
 */

export type Drug = {
  id: string;
  name: string; // الاسم العلمي
  ar: string; // الاسم بالعربية
  brands: string[]; // أسماء تجارية شائعة
  className: string; // المجموعة الدوائية
  subtitle: string;
  atc: string; // WHO ATC code
  legal: "OTC" | "Rx" | "OTC/Rx";
  route: string;
  pregnancy: string;
  ages: string;
  strengths: string[];
  forms: string[];
  uses: string[];
  doses: { adult: string; pediatric: string; max: string; notes: string[] };
  sideEffects: string[];
  contraindications: string[];
  interactions: string[];
  counselling: string[];
  referral: string[];
  source: string;
};

const WHO = "WHO ATC / WHO Model List of Essential Medicines";

export const drugs: Drug[] = [
  {
    id: "paracetamol",
    name: "Paracetamol",
    ar: "باراسيتامول",
    brands: ["Panadol", "Adol", "Fevadol"],
    className: "Analgesic • Antipyretic",
    subtitle: "مسكن وخافض للحرارة",
    atc: "N02BE01",
    legal: "OTC",
    route: "Oral / Rectal / IV",
    pregnancy: "يُعد الخيار المفضل للألم والحمى أثناء الحمل بأقل جرعة فعالة",
    ages: "بالغين وأطفال",
    strengths: ["500 mg", "1 g", "120 mg/5 ml", "250 mg/5 ml"],
    forms: ["أقراص", "كبسولات", "شراب", "تحاميل", "محلول وريدي"],
    uses: ["الألم الخفيف إلى المتوسط", "خفض الحرارة", "الصداع وألم الأسنان", "آلام العضلات"],
    doses: {
      adult: "500–1000 مغ كل 4–6 ساعات",
      pediatric: "10–15 مغ/كغ كل 4–6 ساعات",
      max: "4 غ يوميًا للبالغين (أقل في أمراض الكبد أو تناول الكحول)",
      notes: ["لا تتجاوز 4 جرعات للطفل في 24 ساعة", "انتبه للمستحضرات المركبة التي تحتوي باراسيتامول"],
    },
    sideEffects: ["نادرة بالجرعات العلاجية", "طفح جلدي", "سمية كبدية عند الجرعة الزائدة"],
    contraindications: ["فرط الحساسية", "القصور الكبدي الشديد"],
    interactions: ["الوارفارين (مراقبة INR مع الاستخدام المطول)", "الكحول — زيادة خطر سمية الكبد"],
    counselling: ["لا تجمع أكثر من مستحضر يحتوي باراسيتامول", "يمكن تناوله مع أو بدون طعام"],
    referral: ["حمى > 3 أيام", "ألم شديد لا يستجيب", "اشتباه جرعة زائدة — إحالة فورية"],
    source: WHO,
  },
  {
    id: "ibuprofen",
    name: "Ibuprofen",
    ar: "إيبوبروفين",
    brands: ["Brufen", "Advil"],
    className: "NSAID",
    subtitle: "مضاد التهاب غير ستيرويدي",
    atc: "M01AE01",
    legal: "OTC",
    route: "Oral / Topical",
    pregnancy: "يُتجنب خصوصًا بعد الأسبوع 20 وممنوع في الثلث الأخير",
    ages: "من عمر 3 أشهر فأكثر",
    strengths: ["200 mg", "400 mg", "600 mg", "100 mg/5 ml"],
    forms: ["أقراص", "شراب", "جل موضعي"],
    uses: ["الألم الالتهابي", "خفض الحرارة", "عسر الطمث", "آلام المفاصل والعضلات"],
    doses: {
      adult: "200–400 مغ كل 6–8 ساعات",
      pediatric: "5–10 مغ/كغ كل 6–8 ساعات",
      max: "1200 مغ يوميًا بدون وصفة",
      notes: ["يؤخذ بعد الطعام", "استخدم أقل جرعة ولأقصر مدة"],
    },
    sideEffects: ["عسر هضم وألم معدي", "غثيان", "احتباس سوائل", "ارتفاع ضغط الدم"],
    contraindications: ["قرحة هضمية نشطة", "قصور كلوي شديد", "ربو متفاقم بالأسبرين/NSAIDs"],
    interactions: ["مضادات التخثر — نزيف", "ACE inhibitors + مدرات — أذية كلوية", "أسبرين جرعة منخفضة"],
    counselling: ["تناوله مع الطعام", "أبلغ عن براز أسود أو ألم معدي مستمر"],
    referral: ["نزيف هضمي", "ألم مستمر أكثر من 10 أيام", "حامل في الثلث الأخير"],
    source: WHO,
  },
  {
    id: "diclofenac",
    name: "Diclofenac",
    ar: "ديكلوفيناك",
    brands: ["Voltaren"],
    className: "NSAID",
    subtitle: "مضاد التهاب غير ستيرويدي",
    atc: "M01AB05",
    legal: "Rx",
    route: "Oral / Topical / IM",
    pregnancy: "يُتجنب — ممنوع في الثلث الأخير",
    ages: "بالغين",
    strengths: ["50 mg", "75 mg", "1% gel"],
    forms: ["أقراص", "جل", "حقن عضلي", "تحاميل"],
    uses: ["ألم والتهاب المفاصل", "ألم أسفل الظهر", "آلام ما بعد الإصابات"],
    doses: {
      adult: "50 مغ 2–3 مرات يوميًا",
      pediatric: "غير مفضل عمومًا",
      max: "150 مغ يوميًا",
      notes: ["أعلى خطر قلبي وعائي بين الـ NSAIDs الشائعة"],
    },
    sideEffects: ["اضطراب معدي", "ارتفاع إنزيمات الكبد", "صداع"],
    contraindications: ["مرض قلبي إقفاري", "قرحة نشطة", "قصور كلوي"],
    interactions: ["Warfarin", "Lithium", "Methotrexate"],
    counselling: ["يؤخذ بعد الطعام", "الجل الموضعي خيار أأمن للألم الموضعي"],
    referral: ["ألم صدري", "نزيف هضمي", "تورم ووذمة"],
    source: WHO,
  },
  {
    id: "naproxen",
    name: "Naproxen",
    ar: "نابروكسين",
    brands: ["Naprosyn"],
    className: "NSAID",
    subtitle: "مضاد التهاب طويل المفعول",
    atc: "M01AE02",
    legal: "Rx",
    route: "Oral",
    pregnancy: "يُتجنب",
    ages: "بالغين",
    strengths: ["250 mg", "500 mg"],
    forms: ["أقراص"],
    uses: ["التهاب المفاصل", "النقرس الحاد", "عسر الطمث"],
    doses: {
      adult: "250–500 مغ مرتين يوميًا",
      pediatric: "حسب الوزن وبإشراف طبي",
      max: "1000 مغ يوميًا",
      notes: ["مدة تأثير أطول تسمح بجرعتين يوميًا"],
    },
    sideEffects: ["عسر هضم", "دوخة", "احتباس سوائل"],
    contraindications: ["قرحة هضمية", "قصور كلوي شديد"],
    interactions: ["مضادات التخثر", "مدرات البول", "ACE inhibitors"],
    counselling: ["مع الطعام", "أكثر أمانًا قلبيًا نسبيًا من الديكلوفيناك"],
    referral: ["نزيف", "ألم لا يستجيب"],
    source: WHO,
  },
  {
    id: "aspirin",
    name: "Aspirin",
    ar: "أسبرين",
    brands: ["Aspocid", "Juspirin"],
    className: "NSAID • Antiplatelet",
    subtitle: "مسكن ومضاد للصفيحات",
    atc: "B01AC06",
    legal: "OTC",
    route: "Oral",
    pregnancy: "الجرعات المسكنة تُتجنب؛ الجرعة المنخفضة بإشراف طبي",
    ages: "بالغين — ممنوع تحت 16 سنة",
    strengths: ["75 mg", "81 mg", "300 mg"],
    forms: ["أقراص", "أقراص معوية التغليف"],
    uses: ["الوقاية الثانوية من الجلطات", "مسكن وخافض حرارة (بالغين)"],
    doses: {
      adult: "75–100 مغ يوميًا كمضاد صفيحات",
      pediatric: "ممنوع — خطر متلازمة راي",
      max: "حسب الاستطباب",
      notes: ["الجرعة المنخفضة لا تُستخدم كمسكن"],
    },
    sideEffects: ["نزيف", "عسر هضم", "طنين بالجرعات العالية"],
    contraindications: ["أطفال ومراهقون مع عدوى فيروسية", "قرحة نشطة", "اضطرابات نزفية"],
    interactions: ["مضادات التخثر", "NSAIDs أخرى", "Methotrexate"],
    counselling: ["يؤخذ مع الطعام", "أبلغ عن كدمات أو نزيف غير معتاد"],
    referral: ["نزيف نشط", "قيء دموي"],
    source: WHO,
  },
  {
    id: "amoxicillin",
    name: "Amoxicillin",
    ar: "أموكسيسيلين",
    brands: ["Amoxil", "Julphamox"],
    className: "Penicillin antibiotic",
    subtitle: "مضاد حيوي بيتالاكتام",
    atc: "J01CA04",
    legal: "Rx",
    route: "Oral",
    pregnancy: "يُعد آمنًا نسبيًا بإشراف طبي",
    ages: "بالغين وأطفال",
    strengths: ["250 mg", "500 mg", "125 mg/5 ml", "250 mg/5 ml"],
    forms: ["كبسولات", "أقراص", "معلق فموي"],
    uses: ["التهابات الجهاز التنفسي", "التهاب الأذن الوسطى", "التهابات المسالك البولية", "عدوى الأسنان"],
    doses: {
      adult: "500 مغ كل 8 ساعات",
      pediatric: "25–50 مغ/كغ/اليوم مقسمة كل 8 ساعات",
      max: "حسب الاستطباب وشدة العدوى",
      notes: ["أكمل مدة العلاج كاملة", "المعلق يُحفظ في الثلاجة بعد التحضير 7–14 يومًا"],
    },
    sideEffects: ["إسهال", "غثيان", "طفح جلدي", "فطريات فموية/مهبلية"],
    contraindications: ["حساسية البنسلينات", "الحذر مع حساسية السيفالوسبورينات"],
    interactions: ["Methotrexate", "موانع الحمل الفموية (احتياط)", "Allopurinol — طفح"],
    counselling: ["رجّ المعلق جيدًا", "أكمل الكورس كاملًا حتى مع التحسن"],
    referral: ["طفح مع صعوبة تنفس", "إسهال مائي شديد", "عدم تحسن بعد 48–72 ساعة"],
    source: WHO,
  },
  {
    id: "co-amoxiclav",
    name: "Amoxicillin/Clavulanate",
    ar: "أموكسيسيلين/كلافولانيك",
    brands: ["Augmentin"],
    className: "Penicillin + beta-lactamase inhibitor",
    subtitle: "مضاد حيوي واسع الطيف",
    atc: "J01CR02",
    legal: "Rx",
    route: "Oral",
    pregnancy: "بإشراف طبي",
    ages: "بالغين وأطفال",
    strengths: ["625 mg", "1 g", "228 mg/5 ml", "457 mg/5 ml"],
    forms: ["أقراص", "معلق فموي"],
    uses: ["التهاب الجيوب", "التهابات تنفسية مقاومة", "عدوى الجلد والأنسجة"],
    doses: {
      adult: "625 مغ كل 8 ساعات أو 1 غ كل 12 ساعة",
      pediatric: "حسب مكون الأموكسيسيلين ووزن الطفل",
      max: "حسب الوصفة",
      notes: ["يؤخذ في بداية الوجبة لتقليل الاضطراب المعدي"],
    },
    sideEffects: ["إسهال (أكثر من الأموكسيسيلين وحده)", "غثيان", "ارتفاع إنزيمات الكبد"],
    contraindications: ["حساسية البنسلين", "يرقان ركودي سابق بالدواء"],
    interactions: ["Warfarin", "Methotrexate"],
    counselling: ["مع بداية الأكل", "أكمل المدة الموصوفة"],
    referral: ["إسهال شديد مستمر", "اصفرار العين"],
    source: WHO,
  },
  {
    id: "azithromycin",
    name: "Azithromycin",
    ar: "أزيثرومايسين",
    brands: ["Zithromax"],
    className: "Macrolide antibiotic",
    subtitle: "ماكروليد",
    atc: "J01FA10",
    legal: "Rx",
    route: "Oral",
    pregnancy: "بإشراف طبي",
    ages: "بالغين وأطفال",
    strengths: ["250 mg", "500 mg", "200 mg/5 ml"],
    forms: ["أقراص", "معلق فموي"],
    uses: ["التهابات تنفسية", "بديل عند حساسية البنسلين", "بعض العدوى المنقولة جنسيًا"],
    doses: {
      adult: "500 مغ يوم 1 ثم 250 مغ لمدة 4 أيام، أو 500 مغ × 3 أيام",
      pediatric: "10 مغ/كغ يوميًا لمدة 3 أيام",
      max: "حسب البروتوكول",
      notes: ["مرة واحدة يوميًا — يحسّن الالتزام"],
    },
    sideEffects: ["غثيان", "ألم بطني", "إسهال", "إطالة QT (نادر)"],
    contraindications: ["حساسية الماكروليدات", "أمراض كبدية شديدة"],
    interactions: ["أدوية تُطيل QT", "مضادات الحموضة المحتوية ألمنيوم/مغنيسيوم", "Warfarin"],
    counselling: ["يمكن أخذه مع الطعام", "افصله ساعتين عن مضادات الحموضة"],
    referral: ["خفقان أو إغماء", "يرقان"],
    source: WHO,
  },
  {
    id: "ciprofloxacin",
    name: "Ciprofloxacin",
    ar: "سيبروفلوكساسين",
    brands: ["Ciprobay"],
    className: "Fluoroquinolone",
    subtitle: "كينولون",
    atc: "J01MA02",
    legal: "Rx",
    route: "Oral / IV",
    pregnancy: "يُتجنب",
    ages: "بالغين — يُتجنب عادة في الأطفال",
    strengths: ["250 mg", "500 mg"],
    forms: ["أقراص", "محلول وريدي", "قطرات عين/أذن"],
    uses: ["التهابات المسالك البولية", "بعض العدوى المعوية", "عدوى معقدة بإشراف طبي"],
    doses: {
      adult: "250–500 مغ كل 12 ساعة",
      pediatric: "حالات خاصة فقط",
      max: "1500 مغ يوميًا",
      notes: ["استخدام رشيد — ليس خط أول للحالات البسيطة"],
    },
    sideEffects: ["اعتلال أوتار وتمزق", "غثيان", "دوخة", "حساسية للضوء"],
    contraindications: ["تاريخ اعتلال أوتار بالكينولونات", "الحمل والرضاعة", "الوهن العضلي"],
    interactions: ["الكالسيوم/الحديد/مضادات الحموضة — تقلل الامتصاص", "Theophylline", "Tizanidine"],
    counselling: ["افصله ساعتين عن الحليب ومكملات الحديد", "أوقفه عند ألم الوتر"],
    referral: ["ألم كعب أو كتف", "تنميل أو تغير مزاجي"],
    source: WHO,
  },
  {
    id: "omeprazole",
    name: "Omeprazole",
    ar: "أوميبرازول",
    brands: ["Losec", "Omez"],
    className: "Proton Pump Inhibitor",
    subtitle: "مثبط مضخة البروتون",
    atc: "A02BC01",
    legal: "OTC/Rx",
    route: "Oral",
    pregnancy: "يُستخدم عند الحاجة بإشراف طبي",
    ages: "بالغين وأطفال (بجرعة موزونة)",
    strengths: ["20 mg", "40 mg"],
    forms: ["كبسولات معوية", "أقراص", "حقن"],
    uses: ["GERD والحموضة", "قرحة المعدة والاثني عشر", "الوقاية من قرحة الـ NSAIDs", "جزء من علاج H. pylori"],
    doses: {
      adult: "20 مغ يوميًا قبل الفطور بـ 30–60 دقيقة",
      pediatric: "حسب الوزن بإشراف طبي",
      max: "40 مغ يوميًا في الحالات المعقدة",
      notes: ["لا تُفتح الكبسولة المعوية إلا حسب التعليمات"],
    },
    sideEffects: ["صداع", "إسهال أو إمساك", "نقص المغنيسيوم وB12 مع الاستخدام المطول"],
    contraindications: ["فرط الحساسية"],
    interactions: ["Clopidogrel (يفضل بانتوبرازول)", "Methotrexate", "أدوية تحتاج وسط حمضي مثل Ketoconazole"],
    counselling: ["قبل الأكل بنصف ساعة", "لا يُستخدم كمسكن فوري للحرقة"],
    referral: ["صعوبة بلع", "نقص وزن غير مفسر", "قيء دموي أو براز أسود"],
    source: WHO,
  },
  {
    id: "famotidine",
    name: "Famotidine",
    ar: "فاموتيدين",
    brands: ["Pepcid"],
    className: "H2 receptor antagonist",
    subtitle: "حاصر مستقبلات H2",
    atc: "A02BA03",
    legal: "OTC/Rx",
    route: "Oral",
    pregnancy: "خيار مقبول للحموضة بإشراف طبي",
    ages: "بالغين وأطفال",
    strengths: ["20 mg", "40 mg"],
    forms: ["أقراص"],
    uses: ["الحموضة العرضية", "GERD الخفيف", "قرحة هضمية"],
    doses: {
      adult: "20 مغ مرتين يوميًا أو 40 مغ ليلًا",
      pediatric: "0.5 مغ/كغ/اليوم بإشراف",
      max: "40–80 مغ يوميًا حسب الحالة",
      notes: ["يعمل أسرع من PPI لكن تأثيره أقل ديمومة"],
    },
    sideEffects: ["صداع", "دوخة", "إمساك"],
    contraindications: ["فرط الحساسية"],
    interactions: ["أدوية تحتاج حموضة للامتصاص", "مضادات الحموضة (فاصل زمني)"],
    counselling: ["يمكن أخذه عند الحاجة قبل الوجبات المحفزة"],
    referral: ["أعراض تنذيرية هضمية", "عدم استجابة بعد أسبوعين"],
    source: WHO,
  },
  {
    id: "metoclopramide",
    name: "Metoclopramide",
    ar: "ميتوكلوبراميد",
    brands: ["Primperan"],
    className: "Antiemetic • Prokinetic",
    subtitle: "مضاد للقيء",
    atc: "A03FA01",
    legal: "Rx",
    route: "Oral / IV / IM",
    pregnancy: "يُستخدم عند الحاجة بإشراف",
    ages: "بالغين — حذر شديد في الصغار",
    strengths: ["10 mg", "5 mg/5 ml"],
    forms: ["أقراص", "شراب", "حقن"],
    uses: ["الغثيان والقيء", "خزل المعدة"],
    doses: {
      adult: "10 مغ حتى 3 مرات يوميًا",
      pediatric: "يُتجنب قدر الإمكان",
      max: "مدة العلاج ≤ 5 أيام",
      notes: ["الاستخدام قصير الأمد فقط"],
    },
    sideEffects: ["أعراض خارج هرمية", "نعاس", "تعب"],
    contraindications: ["انسداد أو نزيف معوي", "باركنسون", "صرع"],
    interactions: ["مضادات الذهان", "Levodopa", "مثبطات الجهاز العصبي"],
    counselling: ["قبل الأكل بـ 30 دقيقة", "أوقفه فورًا عند تشنجات عضلية بالوجه"],
    referral: ["حركات لا إرادية", "قيء مستمر مع جفاف"],
    source: WHO,
  },
  {
    id: "loperamide",
    name: "Loperamide",
    ar: "لوبيراميد",
    brands: ["Imodium"],
    className: "Antidiarrheal",
    subtitle: "مضاد إسهال",
    atc: "A07DA03",
    legal: "OTC",
    route: "Oral",
    pregnancy: "يُتجنب في الثلث الأول",
    ages: "بالغين — لا يُعطى للأطفال < 12 سنة بدون طبيب",
    strengths: ["2 mg"],
    forms: ["كبسولات", "أقراص"],
    uses: ["الإسهال الحاد غير الجرثومي", "الإسهال المزمن الوظيفي"],
    doses: {
      adult: "4 مغ بداية ثم 2 مغ بعد كل براز رخو",
      pediatric: "لا يُنصح دون إشراف",
      max: "16 مغ يوميًا (8 مغ ذاتيًا)",
      notes: ["الإماهة الفموية (ORS) هي الأساس في علاج الإسهال"],
    },
    sideEffects: ["إمساك", "ألم بطني", "دوخة"],
    contraindications: ["إسهال دموي مع حمى", "التهاب القولون التقرحي الحاد", "عدوى بكتيرية غازية"],
    interactions: ["أدوية تُطيل QT بالجرعات العالية", "مثبطات CYP3A4"],
    counselling: ["اشرب محلول الإماهة", "أوقفه عند ظهور حمى أو دم"],
    referral: ["دم في البراز", "حمى عالية", "إسهال > 48 ساعة أو علامات جفاف"],
    source: WHO,
  },
  {
    id: "lactulose",
    name: "Lactulose",
    ar: "لاكتولوز",
    brands: ["Duphalac"],
    className: "Osmotic laxative",
    subtitle: "ملين تناضحي",
    atc: "A06AD11",
    legal: "OTC",
    route: "Oral",
    pregnancy: "خيار مقبول للإمساك",
    ages: "بالغين وأطفال",
    strengths: ["10 g/15 ml"],
    forms: ["شراب"],
    uses: ["الإمساك المزمن", "الاعتلال الدماغي الكبدي"],
    doses: {
      adult: "15–30 مل يوميًا",
      pediatric: "حسب العمر والوزن",
      max: "حسب الاستجابة",
      notes: ["يبدأ التأثير خلال 24–48 ساعة"],
    },
    sideEffects: ["انتفاخ", "غازات", "مغص"],
    contraindications: ["انسداد معوي", "عدم تحمل الجالاكتوز"],
    interactions: ["مضادات الحموضة قد تقلل الفعالية"],
    counselling: ["أكثر من شرب الماء والألياف", "التأثير ليس فوريًا"],
    referral: ["إمساك مع قيء أو ألم شديد", "تغير مفاجئ في عادات الأمعاء"],
    source: WHO,
  },
  {
    id: "cetirizine",
    name: "Cetirizine",
    ar: "سيتريزين",
    brands: ["Zyrtec"],
    className: "Second-generation antihistamine",
    subtitle: "مضاد هيستامين جيل ثانٍ",
    atc: "R06AE07",
    legal: "OTC",
    route: "Oral",
    pregnancy: "من الخيارات المقبولة بإشراف",
    ages: "من عمر سنتين",
    strengths: ["10 mg", "5 mg/5 ml"],
    forms: ["أقراص", "شراب", "نقط"],
    uses: ["التهاب الأنف التحسسي", "الشرى (الأرتيكاريا)", "الحكة التحسسية"],
    doses: {
      adult: "10 مغ مرة يوميًا",
      pediatric: "2.5–5 مغ حسب العمر",
      max: "10 مغ يوميًا",
      notes: ["تقليل الجرعة في القصور الكلوي"],
    },
    sideEffects: ["نعاس خفيف", "جفاف الفم", "صداع"],
    contraindications: ["فرط الحساسية", "قصور كلوي شديد"],
    interactions: ["الكحول ومثبطات الجهاز العصبي"],
    counselling: ["يفضل مساءً إن سبب نعاسًا", "أقل تسكينًا من الجيل الأول"],
    referral: ["تورم الوجه أو صعوبة تنفس — طوارئ"],
    source: WHO,
  },
  {
    id: "loratadine",
    name: "Loratadine",
    ar: "لوراتادين",
    brands: ["Claritine"],
    className: "Second-generation antihistamine",
    subtitle: "مضاد هيستامين غير مسكن",
    atc: "R06AX13",
    legal: "OTC",
    route: "Oral",
    pregnancy: "من الخيارات المقبولة بإشراف",
    ages: "من عمر سنتين",
    strengths: ["10 mg", "5 mg/5 ml"],
    forms: ["أقراص", "شراب"],
    uses: ["حساسية الأنف الموسمية", "الشرى المزمن"],
    doses: {
      adult: "10 مغ مرة يوميًا",
      pediatric: "5 مغ للأطفال 2–12 سنة (< 30 كغ)",
      max: "10 مغ يوميًا",
      notes: ["مناسب لمن يقود أو يعمل بتركيز"],
    },
    sideEffects: ["صداع", "جفاف الفم", "تعب"],
    contraindications: ["فرط الحساسية", "حذر في القصور الكبدي"],
    interactions: ["مثبطات CYP3A4 القوية"],
    counselling: ["مرة واحدة يوميًا في نفس الوقت"],
    referral: ["أعراض تنفسية شديدة", "شرى مستمر أكثر من 6 أسابيع"],
    source: WHO,
  },
  {
    id: "chlorpheniramine",
    name: "Chlorpheniramine",
    ar: "كلورفينيرامين",
    brands: ["Piriton"],
    className: "First-generation antihistamine",
    subtitle: "مضاد هيستامين جيل أول",
    atc: "R06AB04",
    legal: "OTC",
    route: "Oral",
    pregnancy: "بإشراف طبي",
    ages: "بالغين وأطفال > سنتين",
    strengths: ["4 mg", "2 mg/5 ml"],
    forms: ["أقراص", "شراب"],
    uses: ["أعراض الحساسية", "سيلان الأنف المصاحب للزكام"],
    doses: {
      adult: "4 مغ كل 4–6 ساعات",
      pediatric: "حسب العمر",
      max: "24 مغ يوميًا للبالغين",
      notes: ["يسبب نعاسًا واضحًا — تأثير مضاد كوليني"],
    },
    sideEffects: ["نعاس", "جفاف الفم", "تشوش رؤية", "احتباس بولي"],
    contraindications: ["الزرق مغلق الزاوية", "تضخم البروستاتا", "الرضّع"],
    interactions: ["الكحول", "المهدئات", "مضادات الاكتئاب"],
    counselling: ["لا تقد السيارة بعد تناوله"],
    referral: ["ارتباك عند كبار السن"],
    source: WHO,
  },
  {
    id: "salbutamol",
    name: "Salbutamol",
    ar: "سالبوتامول",
    brands: ["Ventolin"],
    className: "Short-acting beta-2 agonist",
    subtitle: "موسّع قصبات سريع",
    atc: "R03AC02",
    legal: "Rx",
    route: "Inhalation / Nebulizer / Oral",
    pregnancy: "يُستخدم عند الحاجة — السيطرة على الربو أولوية",
    ages: "بالغين وأطفال",
    strengths: ["100 mcg/puff", "2.5 mg/2.5 ml"],
    forms: ["بخاخ MDI", "محلول استنشاق", "شراب"],
    uses: ["نوبة الربو الحادة", "تشنج القصبات", "الوقاية من ربو الجهد"],
    doses: {
      adult: "1–2 بخة عند الحاجة",
      pediatric: "1–2 بخة مع سبيسر",
      max: "الاستخدام المتكرر يعني ربوًا غير مسيطر عليه",
      notes: ["استخدم سبيسر لتحسين الوصول للرئة"],
    },
    sideEffects: ["رجفة", "خفقان", "صداع", "نقص بوتاسيوم بالجرعات العالية"],
    contraindications: ["فرط الحساسية — حذر في اضطراب النظم"],
    interactions: ["حاصرات بيتا غير الانتقائية", "مدرات البول (بوتاسيوم)"],
    counselling: ["رجّ البخاخ", "اشطف الفم إن استخدمت كورتيزون استنشاقي معه", "بخاخ الإنقاذ يُحمل دائمًا"],
    referral: ["حاجة للبخاخ > 3 مرات أسبوعيًا", "نوبة لا تستجيب — طوارئ"],
    source: WHO,
  },
  {
    id: "budesonide",
    name: "Budesonide (inhaled)",
    ar: "بوديزونيد استنشاقي",
    brands: ["Pulmicort"],
    className: "Inhaled corticosteroid",
    subtitle: "كورتيزون استنشاقي — علاج وقائي",
    atc: "R03BA02",
    legal: "Rx",
    route: "Inhalation",
    pregnancy: "يُفضّل استمرار السيطرة على الربو بإشراف",
    ages: "بالغين وأطفال",
    strengths: ["100 mcg", "200 mcg"],
    forms: ["بخاخ", "محلول استنشاق"],
    uses: ["العلاج الوقائي للربو", "التحكم طويل الأمد بالالتهاب"],
    doses: {
      adult: "200–400 ميكروغرام مرتين يوميًا",
      pediatric: "حسب الشدة والعمر",
      max: "حسب خطة العلاج",
      notes: ["ليس دواء إنقاذ — لا يُستخدم في النوبة الحادة"],
    },
    sideEffects: ["فطريات فموية", "بحة صوت", "تهيج حلق"],
    contraindications: ["عدوى تنفسية فطرية غير معالجة"],
    interactions: ["مثبطات CYP3A4 القوية"],
    counselling: ["اشطف فمك بعد كل استخدام", "الاستخدام يومي حتى بدون أعراض"],
    referral: ["تفاقم الأعراض رغم الالتزام"],
    source: WHO,
  },
  {
    id: "metformin",
    name: "Metformin",
    ar: "ميتفورمين",
    brands: ["Glucophage"],
    className: "Biguanide",
    subtitle: "الخط الأول في السكري النوع الثاني",
    atc: "A10BA02",
    legal: "Rx",
    route: "Oral",
    pregnancy: "يُستخدم في حالات محددة بإشراف",
    ages: "بالغين ومراهقين ≥ 10 سنوات",
    strengths: ["500 mg", "850 mg", "1000 mg"],
    forms: ["أقراص", "أقراص ممتدة المفعول"],
    uses: ["السكري من النوع الثاني", "متلازمة المبيض متعدد الكيسات"],
    doses: {
      adult: "500 مغ 1–2 مرة يوميًا ثم تُرفع تدريجيًا",
      pediatric: "بإشراف اختصاصي",
      max: "2000–2550 مغ يوميًا",
      notes: ["تُرفع الجرعة تدريجيًا لتقليل الأعراض الهضمية"],
    },
    sideEffects: ["إسهال وغثيان", "طعم معدني", "نقص B12 مع الاستخدام المطول", "حماض لبني (نادر جدًا)"],
    contraindications: ["eGFR < 30", "حماض استقلابي حاد", "قصور كبدي شديد"],
    interactions: ["أصبغة التباين اليودية — إيقاف مؤقت", "الكحول", "مدرات البول"],
    counselling: ["مع الطعام أو بعده", "لا يسبب نقص سكر بمفرده عادة"],
    referral: ["تنفس سريع مع ألم عضلي وإرهاق شديد — طوارئ", "قيء مستمر"],
    source: WHO,
  },
  {
    id: "gliclazide",
    name: "Gliclazide",
    ar: "جليكلازيد",
    brands: ["Diamicron"],
    className: "Sulfonylurea",
    subtitle: "محفز إفراز الأنسولين",
    atc: "A10BB09",
    legal: "Rx",
    route: "Oral",
    pregnancy: "يُستبدل عادة بالأنسولين",
    ages: "بالغين",
    strengths: ["30 mg MR", "60 mg MR", "80 mg"],
    forms: ["أقراص", "أقراص معدلة التحرر"],
    uses: ["السكري من النوع الثاني عند عدم كفاية الميتفورمين"],
    doses: {
      adult: "30–120 مغ MR مع الفطور",
      pediatric: "غير مستخدم",
      max: "120 مغ MR يوميًا",
      notes: ["أعلى خطر لنقص السكر مقارنة بالميتفورمين"],
    },
    sideEffects: ["نقص سكر الدم", "زيادة وزن", "اضطراب هضمي"],
    contraindications: ["السكري النوع الأول", "الحماض الكيتوني", "قصور كلوي/كبدي شديد"],
    interactions: ["حاصرات بيتا (تخفي أعراض نقص السكر)", "Fluconazole", "الكحول"],
    counselling: ["لا تفوّت الوجبات", "احمل مصدر سكر سريع"],
    referral: ["نوبات نقص سكر متكررة"],
    source: WHO,
  },
  {
    id: "amlodipine",
    name: "Amlodipine",
    ar: "أملوديبين",
    brands: ["Norvasc"],
    className: "Calcium channel blocker (dihydropyridine)",
    subtitle: "حاصر قنوات كالسيوم",
    atc: "C08CA01",
    legal: "Rx",
    route: "Oral",
    pregnancy: "بإشراف — ليس الخط الأول",
    ages: "بالغين",
    strengths: ["5 mg", "10 mg"],
    forms: ["أقراص"],
    uses: ["ارتفاع ضغط الدم", "الذبحة الصدرية المستقرة"],
    doses: {
      adult: "5 مغ يوميًا وتُرفع إلى 10 مغ",
      pediatric: "2.5–5 مغ بإشراف",
      max: "10 مغ يوميًا",
      notes: ["مناسب لكبار السن ولأصحاب البشرة السمراء كخط أول"],
    },
    sideEffects: ["وذمة الكاحلين", "احمرار الوجه", "صداع", "دوخة"],
    contraindications: ["صدمة قلبية", "تضيق أبهري شديد"],
    interactions: ["Simvastatin (حد الجرعة 20 مغ)", "عصير الجريب فروت"],
    counselling: ["الوذمة عرض شائع — أبلغ الطبيب إن أزعجت", "لا توقف الدواء فجأة من تلقاء نفسك"],
    referral: ["وذمة شديدة", "ألم صدري متكرر"],
    source: WHO,
  },
  {
    id: "lisinopril",
    name: "Lisinopril",
    ar: "ليزينوبريل",
    brands: ["Zestril"],
    className: "ACE inhibitor",
    subtitle: "مثبط الإنزيم المحول للأنجيوتنسين",
    atc: "C09AA03",
    legal: "Rx",
    route: "Oral",
    pregnancy: "ممنوع في الحمل",
    ages: "بالغين",
    strengths: ["5 mg", "10 mg", "20 mg"],
    forms: ["أقراص"],
    uses: ["ارتفاع ضغط الدم", "قصور القلب", "الحماية الكلوية في السكري"],
    doses: {
      adult: "10 مغ يوميًا (تبدأ 2.5–5 مغ)",
      pediatric: "بإشراف اختصاصي",
      max: "40 مغ يوميًا",
      notes: ["راقب الكرياتينين والبوتاسيوم بعد البدء"],
    },
    sideEffects: ["سعال جاف", "دوخة", "فرط بوتاسيوم", "وذمة وعائية (نادر)"],
    contraindications: ["الحمل", "وذمة وعائية سابقة", "تضيق شرياني كلوي ثنائي"],
    interactions: ["NSAIDs", "مكملات البوتاسيوم", "Spironolactone"],
    counselling: ["السعال الجاف عرض شائع — يُستبدل بـ ARB عند الحاجة"],
    referral: ["تورم الشفاه أو اللسان — طوارئ", "حمل"],
    source: WHO,
  },
  {
    id: "losartan",
    name: "Losartan",
    ar: "لوسارتان",
    brands: ["Cozaar"],
    className: "Angiotensin receptor blocker (ARB)",
    subtitle: "حاصر مستقبلات الأنجيوتنسين",
    atc: "C09CA01",
    legal: "Rx",
    route: "Oral",
    pregnancy: "ممنوع في الحمل",
    ages: "بالغين",
    strengths: ["50 mg", "100 mg"],
    forms: ["أقراص"],
    uses: ["ارتفاع ضغط الدم", "الحماية الكلوية", "بديل عند سعال ACE inhibitors"],
    doses: {
      adult: "50 مغ يوميًا",
      pediatric: "بإشراف",
      max: "100 مغ يوميًا",
      notes: ["لا يسبب السعال الجاف عادة"],
    },
    sideEffects: ["دوخة", "فرط بوتاسيوم", "تعب"],
    contraindications: ["الحمل", "تضيق شرياني كلوي ثنائي"],
    interactions: ["NSAIDs", "مدرات حافظة للبوتاسيوم", "Lithium"],
    counselling: ["لا يُجمع مع ACE inhibitor"],
    referral: ["إغماء", "حمل"],
    source: WHO,
  },
  {
    id: "bisoprolol",
    name: "Bisoprolol",
    ar: "بيسوبرولول",
    brands: ["Concor"],
    className: "Beta blocker (cardioselective)",
    subtitle: "حاصر بيتا انتقائي",
    atc: "C07AB07",
    legal: "Rx",
    route: "Oral",
    pregnancy: "بإشراف طبي",
    ages: "بالغين",
    strengths: ["2.5 mg", "5 mg", "10 mg"],
    forms: ["أقراص"],
    uses: ["قصور القلب", "الذبحة الصدرية", "ارتفاع ضغط الدم (خط لاحق)"],
    doses: {
      adult: "1.25–10 مغ يوميًا حسب التحمل",
      pediatric: "غير مستخدم عادة",
      max: "10 مغ يوميًا",
      notes: ["يُرفع تدريجيًا في قصور القلب"],
    },
    sideEffects: ["بطء قلب", "تعب", "برودة الأطراف", "دوخة"],
    contraindications: ["بطء قلب شديد", "حصار قلبي درجة 2–3", "ربو غير مسيطر عليه"],
    interactions: ["Verapamil/Diltiazem", "أدوية السكري (إخفاء نقص السكر)"],
    counselling: ["لا توقفه فجأة — خطر ذبحة أو ارتفاع ضغط ارتدادي"],
    referral: ["نبض < 50", "ضيق نفس متزايد"],
    source: WHO,
  },
  {
    id: "hydrochlorothiazide",
    name: "Hydrochlorothiazide",
    ar: "هيدروكلوروثيازيد",
    brands: ["Esidrex"],
    className: "Thiazide diuretic",
    subtitle: "مدر بول ثيازيدي",
    atc: "C03AA03",
    legal: "Rx",
    route: "Oral",
    pregnancy: "يُتجنب عادة",
    ages: "بالغين",
    strengths: ["12.5 mg", "25 mg"],
    forms: ["أقراص", "تركيبات مشتركة"],
    uses: ["ارتفاع ضغط الدم", "الوذمة"],
    doses: {
      adult: "12.5–25 مغ صباحًا",
      pediatric: "بإشراف",
      max: "50 مغ يوميًا",
      notes: ["يؤخذ صباحًا لتجنب التبول الليلي"],
    },
    sideEffects: ["نقص بوتاسيوم وصوديوم", "ارتفاع حمض اليوريك", "ارتفاع سكر الدم"],
    contraindications: ["نقص بوتاسيوم شديد", "النقرس غير المسيطر عليه", "قصور كلوي شديد"],
    interactions: ["Digoxin", "Lithium", "NSAIDs"],
    counselling: ["صباحًا", "استخدم واقي شمس — حساسية ضوئية"],
    referral: ["تشنجات عضلية شديدة", "نوبة نقرس"],
    source: WHO,
  },
  {
    id: "hydrocortisone-topical",
    name: "Hydrocortisone 1% cream",
    ar: "هيدروكورتيزون موضعي",
    brands: ["Cortizone"],
    className: "Topical corticosteroid (mild)",
    subtitle: "كورتيزون موضعي خفيف",
    atc: "D07AA02",
    legal: "OTC",
    route: "Topical",
    pregnancy: "مقبول لمساحات محدودة",
    ages: "بالغين وأطفال",
    strengths: ["1%"],
    forms: ["كريم", "مرهم", "لوشن"],
    uses: ["الإكزيما الخفيفة", "التهاب الجلد التماسي", "الحكة الالتهابية"],
    doses: {
      adult: "طبقة رقيقة 1–2 مرة يوميًا",
      pediatric: "أقصر مدة وأقل مساحة",
      max: "لا يتجاوز 7 أيام على الوجه بدون إشراف",
      notes: ["لا يُستخدم على الجلد المصاب بعدوى"],
    },
    sideEffects: ["ترقق الجلد مع الاستخدام المطول", "حرقة موضعية", "تغير لون الجلد"],
    contraindications: ["عدوى جلدية فطرية أو بكتيرية غير معالجة", "حب الشباب والوردية"],
    interactions: ["نادرة موضعيًا"],
    counselling: ["كمية قليلة وطبقة رقيقة", "تجنب الوجه والثنيات لفترات طويلة"],
    referral: ["عدم تحسن خلال أسبوع", "علامات عدوى (قيح، حرارة)"],
    source: WHO,
  },
  {
    id: "clotrimazole",
    name: "Clotrimazole",
    ar: "كلوتريمازول",
    brands: ["Canesten"],
    className: "Topical antifungal (azole)",
    subtitle: "مضاد فطريات موضعي",
    atc: "D01AC01",
    legal: "OTC",
    route: "Topical / Vaginal",
    pregnancy: "الاستخدام الموضعي مقبول عمومًا",
    ages: "بالغين وأطفال",
    strengths: ["1%", "2%"],
    forms: ["كريم", "محلول", "تحاميل مهبلية"],
    uses: ["سعفة القدم والجسم", "الكانديدا الجلدية", "الفطريات المهبلية"],
    doses: {
      adult: "مرتين يوميًا لمدة 2–4 أسابيع",
      pediatric: "نفس الاستخدام الموضعي بحذر",
      max: "حسب الحالة",
      notes: ["استمر أسبوعًا بعد اختفاء الأعراض لمنع النكس"],
    },
    sideEffects: ["حرقة موضعية", "احمرار", "حكة"],
    contraindications: ["فرط الحساسية"],
    interactions: ["نادرة موضعيًا"],
    counselling: ["جفف المنطقة جيدًا قبل الاستخدام", "لا تشارك المناشف"],
    referral: ["عدم تحسن خلال 4 أسابيع", "مريض سكري بعدوى قدم"],
    source: WHO,
  },
  {
    id: "ors",
    name: "Oral Rehydration Salts",
    ar: "أملاح الإماهة الفموية",
    brands: ["ORS"],
    className: "Rehydration therapy",
    subtitle: "محلول معالجة الجفاف",
    atc: "A07CA",
    legal: "OTC",
    route: "Oral",
    pregnancy: "آمن",
    ages: "كل الأعمار",
    strengths: ["كيس قياسي منخفض الأسمولية"],
    forms: ["مسحوق للتحضير"],
    uses: ["الإسهال والجفاف", "القيء والفقد السوائلي"],
    doses: {
      adult: "200–400 مل بعد كل براز رخو",
      pediatric: "10 مل/كغ بعد كل إسهال",
      max: "حسب الفقد",
      notes: ["أهم علاج للإسهال خصوصًا عند الأطفال"],
    },
    sideEffects: ["غثيان خفيف عند الشرب السريع"],
    contraindications: ["انسداد معوي", "قيء شديد لا يُحتمل"],
    interactions: ["لا يوجد تداخل مهم"],
    counselling: ["يُحضّر بماء نظيف وبالكمية المكتوبة", "يُشرب ببطء بجرعات صغيرة"],
    referral: ["علامات جفاف شديد", "خمول أو عدم تبول"],
    source: WHO,
  },
];

export const drugById = (id: string) => drugs.find((d) => d.id === id);

export const drugByName = (name: string) =>
  drugs.find((d) => d.name.toLowerCase() === name.trim().toLowerCase());

/** اقتراح تلقائي: يدعم الاسم العلمي والتجاري والعربي + التركيز */
export type Suggestion = { drugId: string; label: string };

export function suggestDrugs(query: string, limit = 8): Suggestion[] {
  const q = query.trim().toLowerCase();
  if (q.length < 2) return [];
  const out: Suggestion[] = [];
  for (const d of drugs) {
    const hit =
      d.name.toLowerCase().includes(q) ||
      d.ar.includes(query.trim()) ||
      d.brands.some((b) => b.toLowerCase().includes(q));
    if (!hit) continue;
    out.push({ drugId: d.id, label: d.name });
    for (const s of d.strengths.slice(0, 2)) out.push({ drugId: d.id, label: `${d.name} ${s}` });
    if (out.length >= limit + 4) break;
  }
  return out.slice(0, limit);
}

/** مطابقة تقريبية بسيطة (Levenshtein) للتسامح مع الأخطاء الإملائية */
export function levenshtein(a: string, b: string): number {
  const m = a.length;
  const n = b.length;
  let prev: number[] = Array.from({ length: n + 1 }, (_, j) => j);
  for (let i = 1; i <= m; i++) {
    const cur: number[] = [i];
    for (let j = 1; j <= n; j++) {
      const cost = a.charAt(i - 1) === b.charAt(j - 1) ? 0 : 1;
      cur[j] = Math.min((prev[j] ?? 0) + 1, (cur[j - 1] ?? 0) + 1, (prev[j - 1] ?? 0) + cost);
    }
    prev = cur;
  }
  return prev[n] ?? 0;
}

export function fuzzyMatch(input: string, target: string): boolean {
  const a = input.trim().toLowerCase();
  const b = target.trim().toLowerCase();
  if (!a) return false;
  if (a === b) return true;
  if (b.startsWith(a) && a.length >= b.length - 2) return true;
  const tolerance = b.length > 8 ? 2 : 1;
  return levenshtein(a, b) <= tolerance;
}
