/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthNewPasswordRouteImport } from './routes/auth.new-password'
import { Route as AuthOtpRouteImport } from './routes/auth.otp'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentCasesRouteImport } from './routes/student.cases'
import { Route as StudentDrugImagesRouteImport } from './routes/student.drug-images'
import { Route as StudentDrugQuestionsRouteImport } from './routes/student.drug-questions'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentPrescriptionsRouteImport } from './routes/student.prescriptions'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentSavedRouteImport } from './routes/student.saved'
import { Route as StudentTrainingRouteImport } from './routes/student.training'
import { Route as StudentTrainingCenterRouteImport } from './routes/student.training-center'
import { Route as StudentCoursesIndexRouteImport } from './routes/student.courses.index'
import { Route as StudentCoursesCourseIdRouteImport } from './routes/student.courses.$courseId'
import { Route as StudentPharmaciesIndexRouteImport } from './routes/student.pharmacies.index'
import { Route as StudentPharmaciesPharmacyIdRouteImport } from './routes/student.pharmacies.$pharmacyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNewPasswordRoute = AuthNewPasswordRouteImport.update({
  id: '/auth/new-password',
  path: '/auth/new-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCasesRoute = StudentCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDrugImagesRoute = StudentDrugImagesRouteImport.update({
  id: '/drug-images',
  path: '/drug-images',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDrugQuestionsRoute = StudentDrugQuestionsRouteImport.update({
  id: '/drug-questions',
  path: '/drug-questions',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPrescriptionsRoute = StudentPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSavedRoute = StudentSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTrainingRoute = StudentTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTrainingCenterRoute = StudentTrainingCenterRouteImport.update({
  id: '/training-center',
  path: '/training-center',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesIndexRoute = StudentCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesCourseIdRoute = StudentCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPharmaciesIndexRoute = StudentPharmaciesIndexRouteImport.update({
  id: '/pharmacies/',
  path: '/pharmacies/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPharmaciesPharmacyIdRoute =
  StudentPharmaciesPharmacyIdRouteImport.update({
    id: '/pharmacies/$pharmacyId',
    path: '/pharmacies/$pharmacyId',
    getParentRoute: () => StudentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/design-system': typeof DesignSystemRoute
  '/language': typeof LanguageRoute
  '/onboarding': typeof OnboardingRoute
  '/student': typeof StudentRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/new-password': typeof AuthNewPasswordRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/student/cases': typeof StudentCasesRoute
  '/student/drug-images': typeof StudentDrugImagesRoute
  '/student/drug-questions': typeof StudentDrugQuestionsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/prescriptions': typeof StudentPrescriptionsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/saved': typeof StudentSavedRoute
  '/student/training': typeof StudentTrainingRoute
  '/student/training-center': typeof StudentTrainingCenterRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
  '/student/pharmacies/$pharmacyId': typeof StudentPharmaciesPharmacyIdRoute
  '/student/courses/': typeof StudentCoursesIndexRoute
  '/student/pharmacies/': typeof StudentPharmaciesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/design-system': typeof DesignSystemRoute
  '/language': typeof LanguageRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/new-password': typeof AuthNewPasswordRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/student/cases': typeof StudentCasesRoute
  '/student/drug-images': typeof StudentDrugImagesRoute
  '/student/drug-questions': typeof StudentDrugQuestionsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/prescriptions': typeof StudentPrescriptionsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/saved': typeof StudentSavedRoute
  '/student/training': typeof StudentTrainingRoute
  '/student/training-center': typeof StudentTrainingCenterRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
  '/student/pharmacies/$pharmacyId': typeof StudentPharmaciesPharmacyIdRoute
  '/student/courses': typeof StudentCoursesIndexRoute
  '/student/pharmacies': typeof StudentPharmaciesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/design-system': typeof DesignSystemRoute
  '/language': typeof LanguageRoute
  '/onboarding': typeof OnboardingRoute
  '/student': typeof StudentRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/new-password': typeof AuthNewPasswordRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/student/cases': typeof StudentCasesRoute
  '/student/drug-images': typeof StudentDrugImagesRoute
  '/student/drug-questions': typeof StudentDrugQuestionsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/prescriptions': typeof StudentPrescriptionsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/saved': typeof StudentSavedRoute
  '/student/training': typeof StudentTrainingRoute
  '/student/training-center': typeof StudentTrainingCenterRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
  '/student/pharmacies/$pharmacyId': typeof StudentPharmaciesPharmacyIdRoute
  '/student/courses/': typeof StudentCoursesIndexRoute
  '/student/pharmacies/': typeof StudentPharmaciesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/design-system'
    | '/language'
    | '/onboarding'
    | '/student'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/new-password'
    | '/auth/otp'
    | '/auth/register'
    | '/student/cases'
    | '/student/drug-images'
    | '/student/drug-questions'
    | '/student/notifications'
    | '/student/prescriptions'
    | '/student/profile'
    | '/student/saved'
    | '/student/training'
    | '/student/training-center'
    | '/admin/'
    | '/student/'
    | '/student/courses/$courseId'
    | '/student/pharmacies/$pharmacyId'
    | '/student/courses/'
    | '/student/pharmacies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/design-system'
    | '/language'
    | '/onboarding'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/new-password'
    | '/auth/otp'
    | '/auth/register'
    | '/student/cases'
    | '/student/drug-images'
    | '/student/drug-questions'
    | '/student/notifications'
    | '/student/prescriptions'
    | '/student/profile'
    | '/student/saved'
    | '/student/training'
    | '/student/training-center'
    | '/admin'
    | '/student'
    | '/student/courses/$courseId'
    | '/student/pharmacies/$pharmacyId'
    | '/student/courses'
    | '/student/pharmacies'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/design-system'
    | '/language'
    | '/onboarding'
    | '/student'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/new-password'
    | '/auth/otp'
    | '/auth/register'
    | '/student/cases'
    | '/student/drug-images'
    | '/student/drug-questions'
    | '/student/notifications'
    | '/student/prescriptions'
    | '/student/profile'
    | '/student/saved'
    | '/student/training'
    | '/student/training-center'
    | '/admin/'
    | '/student/'
    | '/student/courses/$courseId'
    | '/student/pharmacies/$pharmacyId'
    | '/student/courses/'
    | '/student/pharmacies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  DesignSystemRoute: typeof DesignSystemRoute
  LanguageRoute: typeof LanguageRoute
  OnboardingRoute: typeof OnboardingRoute
  StudentRoute: typeof StudentRouteWithChildren
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthNewPasswordRoute: typeof AuthNewPasswordRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/new-password': {
      id: '/auth/new-password'
      path: '/auth/new-password'
      fullPath: '/auth/new-password'
      preLoaderRoute: typeof AuthNewPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/cases': {
      id: '/student/cases'
      path: '/cases'
      fullPath: '/student/cases'
      preLoaderRoute: typeof StudentCasesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/drug-images': {
      id: '/student/drug-images'
      path: '/drug-images'
      fullPath: '/student/drug-images'
      preLoaderRoute: typeof StudentDrugImagesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/drug-questions': {
      id: '/student/drug-questions'
      path: '/drug-questions'
      fullPath: '/student/drug-questions'
      preLoaderRoute: typeof StudentDrugQuestionsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/prescriptions': {
      id: '/student/prescriptions'
      path: '/prescriptions'
      fullPath: '/student/prescriptions'
      preLoaderRoute: typeof StudentPrescriptionsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/saved': {
      id: '/student/saved'
      path: '/saved'
      fullPath: '/student/saved'
      preLoaderRoute: typeof StudentSavedRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/training': {
      id: '/student/training'
      path: '/training'
      fullPath: '/student/training'
      preLoaderRoute: typeof StudentTrainingRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/training-center': {
      id: '/student/training-center'
      path: '/training-center'
      fullPath: '/student/training-center'
      preLoaderRoute: typeof StudentTrainingCenterRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses/': {
      id: '/student/courses/'
      path: '/courses'
      fullPath: '/student/courses/'
      preLoaderRoute: typeof StudentCoursesIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses/$courseId': {
      id: '/student/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/student/courses/$courseId'
      preLoaderRoute: typeof StudentCoursesCourseIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/pharmacies/': {
      id: '/student/pharmacies/'
      path: '/pharmacies'
      fullPath: '/student/pharmacies/'
      preLoaderRoute: typeof StudentPharmaciesIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/pharmacies/$pharmacyId': {
      id: '/student/pharmacies/$pharmacyId'
      path: '/pharmacies/$pharmacyId'
      fullPath: '/student/pharmacies/$pharmacyId'
      preLoaderRoute: typeof StudentPharmaciesPharmacyIdRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentCasesRoute: typeof StudentCasesRoute
  StudentDrugImagesRoute: typeof StudentDrugImagesRoute
  StudentDrugQuestionsRoute: typeof StudentDrugQuestionsRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentPrescriptionsRoute: typeof StudentPrescriptionsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentSavedRoute: typeof StudentSavedRoute
  StudentTrainingRoute: typeof StudentTrainingRoute
  StudentTrainingCenterRoute: typeof StudentTrainingCenterRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentCoursesCourseIdRoute: typeof StudentCoursesCourseIdRoute
  StudentPharmaciesPharmacyIdRoute: typeof StudentPharmaciesPharmacyIdRoute
  StudentCoursesIndexRoute: typeof StudentCoursesIndexRoute
  StudentPharmaciesIndexRoute: typeof StudentPharmaciesIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCasesRoute: StudentCasesRoute,
  StudentDrugImagesRoute: StudentDrugImagesRoute,
  StudentDrugQuestionsRoute: StudentDrugQuestionsRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentPrescriptionsRoute: StudentPrescriptionsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentSavedRoute: StudentSavedRoute,
  StudentTrainingRoute: StudentTrainingRoute,
  StudentTrainingCenterRoute: StudentTrainingCenterRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentCoursesCourseIdRoute: StudentCoursesCourseIdRoute,
  StudentPharmaciesPharmacyIdRoute: StudentPharmaciesPharmacyIdRoute,
  StudentCoursesIndexRoute: StudentCoursesIndexRoute,
  StudentPharmaciesIndexRoute: StudentPharmaciesIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  DesignSystemRoute: DesignSystemRoute,
  LanguageRoute: LanguageRoute,
  OnboardingRoute: OnboardingRoute,
  StudentRoute: StudentRouteWithChildren,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthNewPasswordRoute: AuthNewPasswordRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
