/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AuthAccountTypeRouteImport } from './routes/auth.account-type'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthNewPasswordRouteImport } from './routes/auth.new-password'
import { Route as AuthOtpRouteImport } from './routes/auth.otp'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentTrainingRouteImport } from './routes/student.training'
import { Route as StudentCoursesIndexRouteImport } from './routes/student.courses.index'
import { Route as StudentCoursesCourseIdRouteImport } from './routes/student.courses.$courseId'
import { Route as StudentPharmaciesIndexRouteImport } from './routes/student.pharmacies.index'
import { Route as StudentPharmaciesPharmacyIdRouteImport } from './routes/student.pharmacies.$pharmacyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAccountTypeRoute = AuthAccountTypeRouteImport.update({
  id: '/auth/account-type',
  path: '/auth/account-type',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNewPasswordRoute = AuthNewPasswordRouteImport.update({
  id: '/auth/new-password',
  path: '/auth/new-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTrainingRoute = StudentTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesIndexRoute = StudentCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesCourseIdRoute = StudentCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPharmaciesIndexRoute = StudentPharmaciesIndexRouteImport.update({
  id: '/pharmacies/',
  path: '/pharmacies/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPharmaciesPharmacyIdRoute =
  StudentPharmaciesPharmacyIdRouteImport.update({
    id: '/pharmacies/$pharmacyId',
    path: '/pharmacies/$pharmacyId',
    getParentRoute: () => StudentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/language': typeof LanguageRoute
  '/onboarding': typeof OnboardingRoute
  '/student': typeof StudentRouteWithChildren
  '/auth/account-type': typeof AuthAccountTypeRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/new-password': typeof AuthNewPasswordRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/student/training': typeof StudentTrainingRoute
  '/student/': typeof StudentIndexRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
  '/student/pharmacies/$pharmacyId': typeof StudentPharmaciesPharmacyIdRoute
  '/student/courses/': typeof StudentCoursesIndexRoute
  '/student/pharmacies/': typeof StudentPharmaciesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/language': typeof LanguageRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/account-type': typeof AuthAccountTypeRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/new-password': typeof AuthNewPasswordRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/student/training': typeof StudentTrainingRoute
  '/student': typeof StudentIndexRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
  '/student/pharmacies/$pharmacyId': typeof StudentPharmaciesPharmacyIdRoute
  '/student/courses': typeof StudentCoursesIndexRoute
  '/student/pharmacies': typeof StudentPharmaciesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/language': typeof LanguageRoute
  '/onboarding': typeof OnboardingRoute
  '/student': typeof StudentRouteWithChildren
  '/auth/account-type': typeof AuthAccountTypeRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/new-password': typeof AuthNewPasswordRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/student/training': typeof StudentTrainingRoute
  '/student/': typeof StudentIndexRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
  '/student/pharmacies/$pharmacyId': typeof StudentPharmaciesPharmacyIdRoute
  '/student/courses/': typeof StudentCoursesIndexRoute
  '/student/pharmacies/': typeof StudentPharmaciesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/language'
    | '/onboarding'
    | '/student'
    | '/auth/account-type'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/new-password'
    | '/auth/otp'
    | '/auth/register'
    | '/student/training'
    | '/student/'
    | '/student/courses/$courseId'
    | '/student/pharmacies/$pharmacyId'
    | '/student/courses/'
    | '/student/pharmacies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/language'
    | '/onboarding'
    | '/auth/account-type'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/new-password'
    | '/auth/otp'
    | '/auth/register'
    | '/student/training'
    | '/student'
    | '/student/courses/$courseId'
    | '/student/pharmacies/$pharmacyId'
    | '/student/courses'
    | '/student/pharmacies'
  id:
    | '__root__'
    | '/'
    | '/language'
    | '/onboarding'
    | '/student'
    | '/auth/account-type'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/new-password'
    | '/auth/otp'
    | '/auth/register'
    | '/student/training'
    | '/student/'
    | '/student/courses/$courseId'
    | '/student/pharmacies/$pharmacyId'
    | '/student/courses/'
    | '/student/pharmacies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LanguageRoute: typeof LanguageRoute
  OnboardingRoute: typeof OnboardingRoute
  StudentRoute: typeof StudentRouteWithChildren
  AuthAccountTypeRoute: typeof AuthAccountTypeRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthNewPasswordRoute: typeof AuthNewPasswordRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/account-type': {
      id: '/auth/account-type'
      path: '/auth/account-type'
      fullPath: '/auth/account-type'
      preLoaderRoute: typeof AuthAccountTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/new-password': {
      id: '/auth/new-password'
      path: '/auth/new-password'
      fullPath: '/auth/new-password'
      preLoaderRoute: typeof AuthNewPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/training': {
      id: '/student/training'
      path: '/training'
      fullPath: '/student/training'
      preLoaderRoute: typeof StudentTrainingRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses/': {
      id: '/student/courses/'
      path: '/courses'
      fullPath: '/student/courses/'
      preLoaderRoute: typeof StudentCoursesIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses/$courseId': {
      id: '/student/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/student/courses/$courseId'
      preLoaderRoute: typeof StudentCoursesCourseIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/pharmacies/': {
      id: '/student/pharmacies/'
      path: '/pharmacies'
      fullPath: '/student/pharmacies/'
      preLoaderRoute: typeof StudentPharmaciesIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/pharmacies/$pharmacyId': {
      id: '/student/pharmacies/$pharmacyId'
      path: '/pharmacies/$pharmacyId'
      fullPath: '/student/pharmacies/$pharmacyId'
      preLoaderRoute: typeof StudentPharmaciesPharmacyIdRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface StudentRouteChildren {
  StudentTrainingRoute: typeof StudentTrainingRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentCoursesCourseIdRoute: typeof StudentCoursesCourseIdRoute
  StudentPharmaciesPharmacyIdRoute: typeof StudentPharmaciesPharmacyIdRoute
  StudentCoursesIndexRoute: typeof StudentCoursesIndexRoute
  StudentPharmaciesIndexRoute: typeof StudentPharmaciesIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentTrainingRoute: StudentTrainingRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentCoursesCourseIdRoute: StudentCoursesCourseIdRoute,
  StudentPharmaciesPharmacyIdRoute: StudentPharmaciesPharmacyIdRoute,
  StudentCoursesIndexRoute: StudentCoursesIndexRoute,
  StudentPharmaciesIndexRoute: StudentPharmaciesIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LanguageRoute: LanguageRoute,
  OnboardingRoute: OnboardingRoute,
  StudentRoute: StudentRouteWithChildren,
  AuthAccountTypeRoute: AuthAccountTypeRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthNewPasswordRoute: AuthNewPasswordRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
